### PR TITLE
Login

### LINKED ISSUE #44: Implement Login/Singup/Logout feature

### PR DESCRIPTION
**Pull request by Lada496**
### Feature Description
✅ Login/Logout/Signup feature
✅ Remember me feature during login: extend the expiration time to be 30 days from the last login if users choose it. (the default is 15 min)

### Related Issue
close #44 

#### What I want to discuss
- Logout button design and position: I temporary put the button in Navbar without adding any fancy stylings but I'm sure it can be better
- Do we want to use Route Handlers[https://nextjs.org/docs/app/building-your-application/routing/router-handlers] to make it consistent: I used Route Handlers to leverage cookies[https://nextjs.org/docs/app/api-reference/functions/cookies] because it only available with Route Handlers and now I'm wondering if we should migrate other apis as well. One of main props is just look nicer and cons is obviously there is a risk to face another hell...
- I put prebuild command `npx prisma migrate dev` to make sure the deployed database is updated but not sure if this is okay way. Let me know if you have any suggestion.

#### Refs and explanation
- [Basic way to implement nextauth with Route Handlers](https://next-auth.js.org/configuration/initialization#route-handlers-app)
- [How to implement remember me feature discussion](https://github.com/nextauthjs/next-auth/discussions/3794): I get the basic idea from this. The official document about advanced initialization used in the code in the discussion is [here](https://next-auth.js.org/configuration/initialization#advanced-initialization)
- There is a wired symptom during login: when after manually logging out, the first login receive "success" without having session data: It seems like NextAuth send res.end before updating session data. I just fixed it by retrying signIn but I think we can diagnose it.
- How I got "a good value" NEXTAUTH_SECRET: `openssl rand -base64 32` (ref: https://next-auth.js.org/configuration/options#secret)
### Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by SachiGoto** [comment]
Thank you Yuko for working on log in and sign up authentication!  Wonder if there is a preview on netlify so that I can have a look how it works?  
Remember me feature sounds so cool.

**Comment by Lada496** [comment]
> Thank you Yuko for working on log in and sign up authentication! Wonder if there is a preview on netlify so that I can have a look how it works? Remember me feature sounds so cool.

Yeah not sure why it requires an approval🤷‍♀️ @devjoylee could you help me??

**Review by keento0809 — APPROVED** [review]
@Lada496 Thank you for your outstanding contribution! 💯 🙌   After reading codes for almost 2 hours, I could understand the whole structure of authentication, lol

But still I could not understand 100% about the logic of remember-me feature because of my poor understanding of next-auth, so could you demonstrate it in `/app/api/auth/[...nextauth]` at the next meeting?

**Comment by Lada496** [comment]
> @Lada496 Thank you for your outstanding contribution! 💯 🙌 After reading codes for almost 2 hours, I could understand the whole structure of authentication, lol
> 
> But still I could not understand 100% about the logic of remember-me feature because of my poor understanding of next-auth, so could you demonstrate it in `/app/api/auth/[...nextauth]` at the next meeting?

To tell the truth, I also don't 100% understand everything in the file but I'll try my best to explain these logic haha

**Review by devjoylee — COMMENTED** [review]
Thank you @Lada496 for the auth setup
btw I had accepted the deploy last week, but I didn't notice there's build error in it.
Please help take a look and see if this can be solved on your end. 

스크린샷 2023-08-06 오전 9 35 50

**Review by devjoylee — APPROVED** [review]
Thank you for fixing the errors! Looks good to me now :)

**Pull request merged**
