### PR TITLE
FavPage keeps showing "Loading..."

### LINKED ISSUE #101: FavPage keeps showing "Loading..."

### PR DESCRIPTION
**Pull request by keento0809**
### Feature Description

- Fix the issue on FavPage showing "Loading..."
- Fix the file structures same as `(auth)` and `(event)`

https://github.com/van-squad/map-t3/assets/65790344/cdf1c724-c632-4425-a04b-6aaad07cf182

### Related Issue

- close #101 

### Something you want to mention

- I feel like it's better to get `session` on server components and then pass it to client components like this code snippet.
```typescript
import { getServerAuthSession } from "~/server/auth";
import FavListPage from "./compoments/page/FavListPage";

const FavPage = async () => {
  const session = await getServerAuthSession();

  return <FavListPage session={session} />;
};

export default FavPage;
```

### Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by SachiGoto** [comment]
"I feel like it's better to get session on server components and then pass it to client components like this code snippet."

About your comment, if we get session on server components, does it fix the issue of accessing the favs page in production?

**Comment by keento0809** [comment]
> "I feel like it's better to get session on server components and then pass it to client components like this code snippet."
> 
> About your comment, if we get session on server components, does it fix the issue of accessing the favs page in production?

@SachiGoto As long as I've checked on deploy review, it fixes the issue on fav page!!

https://github.com/van-squad/map-t3/assets/65790344/24295737-0d8f-4220-ba4c-8e704e213967

**Comment by SachiGoto** [comment]
> > "I feel like it's better to get session on server components and then pass it to client components like this code snippet."
> > About your comment, if we get session on server components, does it fix the issue of accessing the favs page in production?
> 
> @SachiGoto As long as I've checked on deploy review, it fixes the issue on fav page!!
> 
>  2023-11-03.12.44.03.mov

That's perfect! I just tested with the preview and it works! We definitely should go with what you did! Thank you so much for figuring out the problem!

**Comment by Lada496** [comment]
> * Fix the file structures same as `(auth)` and `(event)`

@keento0809 I'm not sure if we need to use parentheses for `favlist`.
These two folders have sharing components with several pages and we used group routing to avoid affecting the URL.
For example, if we use `auth` without parentheses, the URL will be `/auth/login` and `/auth/signup`, so we leveraged the group routing to get `/login` and `signup`. Let me know if I missed something.   
ref: https://nextjs.org/docs/app/building-your-application/routing/route-groups#organize-routes-without-affecting-the-url-path

**Comment by keento0809** [comment]
@Lada496 Oh actually I didn't realize that `/map` is now located inside `(event)` directory. So you're correct! There is no meaning to do like `(favlist)` from the optimization perspective. I'll return it to the previous one as `favlist`.

**Review by SachiGoto — APPROVED** [review]

**Review by Lada496 — APPROVED** [review]

**Comment by Lada496** [comment]
@keento0809 could you resolve conflicts so that we can merge this PR? Thanks 🙌

**Pull request merged**
