### PR TITLE
Introduce mantine calendar #25

### LINKED ISSUE #25: Introduce mantine calendar
- Mantine calendar should fetch the selected date to show events that are corresponded to event's date

### PR DESCRIPTION
**Pull request by keento0809**
### Feature Description

- Set up calendar component with mantine
- Default date value is set as today's date
- The purpose of this calendar is to select the date that will be passed as the parameter when fetching meetup data from meetup API

https://github.com/van-squad/map-t3/assets/65790344/ce233f70-0a3c-49a9-97a1-a2acccb48ade

### Related Issue

- close #25 

### Something you want to mention

- Please do `npm install` !
- I temporary created `app/calendar/page.tsx` to display the calendar component. Once we've decided where this component should be located, we have to delete `app/calendar/page.tsx` and move the calendar component to `src/components`
- Styles for this component (`src/app/calendar/styles.ts`) are also temporal ones.
- We need to add a new function as the props to this calendar component in order to interact with the process of getting new meetup data with the newly selected date（Currently I've just added a sample React state and dispatch function as the props)
- Default date type of the mantine calendar is `Date`, but I'm not quite sure what date type we need for meetup API. So after the logic for fetching data from meetup API is merged, we'll add a function in `utils/date-converter.ts` to handle this.

### Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Lada496 — COMMENTED** [review]
Hi @keento0809 Thank you for setting up calendar!
Can we move the component under src/app/map/components and  ender it in the map page rather than having an independent page?
As long as I understand, we need the calendar component in the map page.
Screenshot 2023-08-05 at 18 20 54

Figma: https://www.figma.com/file/5JTHosopzXXjY5BFxp8vMf/Map-Project?type=design&node-id=1-1142&mode=design&t=ZmcIHGWWBV3MRXE5-0
Preview: https://www.figma.com/proto/5JTHosopzXXjY5BFxp8vMf/Map-Project?type=design&node-id=1-1142&t=ZmcIHGWWBV3MRXE5-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A3

Please take a look at these links. If it's just for testing purpose to have the calendar page, please ignore my comment. Thanks!

**Comment by keento0809** [comment]
@Lada496 Oh, I've totally not checked the figma file 🙏 , so now I moved it into the `app/map/components` directory and applied it in the google map like this screen shot 😃 
スクリーンショット 2023-08-06 13 32 17

**Review by Lada496 — APPROVED** [review]
Thank you for updating! LGTM!

**Comment by SachiGoto** [comment]
Amazing! Things are coming together! LGTM as well!

**Review by SachiGoto — APPROVED** [review]

**Pull request merged**
